### ISSUE TITLE
docs/quickstart: kind image load fails on Apple M1

### ISSUE THREAD

**Issue by ahmetb** [admiraltyio/admiralty#148] opened 2022-04-06 17:28 UTC
step:
```
images=(
  # cert-manager dependency
  quay.io/jetstack/cert-manager-controller:v1.7.1
  quay.io/jetstack/cert-manager-webhook:v1.7.1
  quay.io/jetstack/cert-manager-cainjector:v1.7.1
  quay.io/jetstack/cert-manager-ctl:v1.7.1
  # admiralty open source
  quay.io/admiralty/multicluster-scheduler-agent:0.15.1
  quay.io/admiralty/multicluster-scheduler-scheduler:0.15.1
  quay.io/admiralty/multicluster-scheduler-remove-finalizers:0.15.1
  quay.io/admiralty/multicluster-scheduler-restarter:0.15.1
)
for image in "${images[@]}"
do
  docker pull $image
  for CLUSTER_NAME in cd us eu
  do
    kind load docker-image $image --name $CLUSTER_NAME
  done
done
```

I am using Docker Desktop on macOS Monterey with M1 chip.

It seems like the instructions might not be working as intended.

```
0.15.1: Pulling from admiralty/multicluster-scheduler-agent
d2547f570c6c: Pull complete
Digest: sha256:13a9a3bb0161438e2d1b92327a39f61dc1a1dca13da1b1d9d40add28c815ccfa
Status: Downloaded newer image for quay.io/admiralty/multicluster-scheduler-agent:0.15.1
quay.io/admiralty/multicluster-scheduler-agent:0.15.1
Image: "quay.io/admiralty/multicluster-scheduler-agent:0.15.1" with ID "sha256:c1465be63b942bd97166d38a2303010c7d1e016c2cfc098af3e378b874bc1045" not yet present on node "cd-control-plane", loading...
ERROR: failed to load image: command "docker exec --privileged -i cd-control-plane ctr --namespace=k8s.io images import --snapshotter overlayfs -" failed with error: exit status 1
Command Output: unpacking quay.io/admiralty/multicluster-scheduler-agent:0.15.1 (sha256:31648a0d3b09dbaae640fe08d8d05dfbef329920f4d1221f2febb5af0610b22b)...ctr: content digest sha256:b0d1c3ac040be7fa7fa11bbe6e5bf2cce9b86f6be20b0d8d3da8cf8ba8da78a6: not found
```

**Comment by ahmetb** [comment] 2022-04-10 21:08
This seems to be the issue https://github.com/kubernetes-sigs/kind/issues/2549 but I am not sure what the resolution is.

**Comment by adrienjt** [comment] 2022-04-14 23:07
Hi @ahmetb, I see that you submitted another issue after this one, #149, where you have gone farther in the quick start guide. Were you able to figure out what the problem is here?

Unfortunately, I don't have an M1 available. We do build multi-arch images that are known to work, though aren't systematically tested... Which version of kind are you running? The latest version seems to address some multi-arch issues (not necessarily related):

> NOTE: these node images support amd64 and arm64 now.
> [...]
> Fix kind load docker-image if all images are already present
https://github.com/kubernetes-sigs/kind/releases/tag/v0.12.0

**Comment by hermanbanken** [comment] 2022-05-15 15:35
I'm seeing the same problem. If I just run a regular `nginx` image from docker hub it works. If I use the local registry route, it also works.

But `kind load docker-image`:
```bash
GOOS=linux GOARCH=arm64 go build -o bin/server example/server
docker build --platform=linux/arm64 -t demo-server-arm64 -f Dockerfile
kind --name=demo load docker-image demo-server-arm64
kubectl create deployment demo-server-arm64 --image demo-server-arm64 --replicas=1
# fails with:
# Failed to pull image "demo-server-arm64": rpc error: code = Unknown desc = failed to pull and unpack
# image "docker.io/library/demo-server-arm64:latest": failed to resolve reference 
# "docker.io/library/demo-server-arm64:latest": pull access denied, repository does not exist 
# or may require authorization: server message: insufficient_scope: authorization failed
```

```bash
GOOS=linux GOARCH=amd64 go build -o bin/server example/server
docker build --platform=linux/amd64 -t demo-server-amd64 -f Dockerfile
kind --name=demo load docker-image demo-server-amd64
# fails with:
# ERROR: failed to load image: command "docker exec --privileged -i demo-control-plane ctr --namespace=k8s.io images import --snapshotter overlayfs -" failed with error: exit status 1
# Command Output: ctr: image might be filtered out
```

(N.B. Dockerfile is just 1 binary `COPY` based on `scratch`)

I have the feeling that somewhere down the line, Kubernetes might be trying to load amd64 images... The fact that NGINX works, can this be because it is a multi-architecture image?

**Comment by adrienjt** [comment] 2023-11-04 04:01
Tested the v0.16 quickstart with an M1. It works. Probably an issue that was fixed with a recent version kind.

**Closed by adrienjt** 2023-11-04 04:01 UTC
